### ISSUE TITLE
Seeing `text file busy` error during protobuf compilation

### ISSUE THREAD

**Issue by MattRMcFarland** [thesamet/sbt-protoc#14]
We're seeing spurious failures on a build server due to the included error (below). This issue was actually reported in the `protoc-jar` repository [here](https://github.com/os72/protoc-jar/issues/8). Seems like a fix was added in this `issue_text_file_busy` [branch](https://github.com/os72/protoc-jar/tree/issue_text_file_busy). 

I saw that this project depends on `"protoc-jar" % "3.1.0.2"`, but the most up to date version is `"protoc-jar" % "3.1.0.3"`. Is there something we can do to use `sbt-protoc` in our project but use that `issue_txt_file_busy` branch of `protoc-jar`? Or do we just have to wait for a fix to come out on `protoc-jar` and have that rolled into this project?

Any help greatly appreciated!

```
Caused by: java.io.IOException: Cannot run program "/tmp/protoc697070785121925936.exe": error=26, Text file busy
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:84)
	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:55)
	at sbtprotoc.ProtocPlugin$$anonfun$protobufGlobalSettings$9$$anonfun$apply$4.apply(ProtocPlugin.scala:56)
	at sbtprotoc.ProtocPlugin$$anonfun$protobufGlobalSettings$9$$anonfun$apply$4.apply(ProtocPlugin.scala:55)
	at protocbridge.ProtocBridge$.runWithGenerators(ProtocBridge.scala:79)
	at protocbridge.ProtocBridge$.run(ProtocBridge.scala:61)
	at sbtprotoc.ProtocPlugin$.executeProtoc(ProtocPlugin.scala:88)
	at sbtprotoc.ProtocPlugin$.sbtprotoc$ProtocPlugin$$compile(ProtocPlugin.scala:112)
	at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1$$anonfun$4.apply(ProtocPlugin.scala:141)
	at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1$$anonfun$4.apply(ProtocPlugin.scala:140)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:249)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:245)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:206)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:245)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:244)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:200)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:244)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:242)
	at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1.apply(ProtocPlugin.scala:150)
	at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1.apply(ProtocPlugin.scala:136)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: error=26, Text file busy
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:84)
	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:55)
	at sbtprotoc.ProtocPlugin$$anonfun$protobufGlobalSettings$9$$anonfun$apply$4.apply(ProtocPlugin.scala:56)
	at sbtprotoc.ProtocPlugin$$anonfun$protobufGlobalSettings$9$$anonfun$apply$4.apply(ProtocPlugin.scala:55)
	at protocbridge.ProtocBridge$.runWithGenerators(ProtocBridge.scala:79)
	at protocbridge.ProtocBridge$.run(ProtocBridge.scala:61)
	at sbtprotoc.ProtocPlugin$.executeProtoc(ProtocPlugin.scala:88)
	at sbtprotoc.ProtocPlugin$.sbtprotoc$ProtocPlugin$$compile(ProtocPlugin.scala:112)
	at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1$$anonfun$4.apply(ProtocPlugin.scala:141)
	at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1$$anonfun$4.apply(ProtocPlugin.scala:140)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:235)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:249)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:245)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:206)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:245)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:244)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:200)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:244)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:242)
	at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1.apply(ProtocPlugin.scala:150)
	at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1.apply(ProtocPlugin.scala:136)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by thesamet** [comment]
Once protoc-jar releases the fix, you will be able to use it by adding the libraryDependency to `project/scalapb.sbt` (note: not your main `build.sbt`). In the meantime, you might want to try to get sbt-protoc to invoke a locally installed `protoc` binary by setting `PB.protoc := {args => Process(protoc.value, args) ! streams.value.log }`

**Comment by os72** [comment]
Fix included in protoc-jar 3.2.0, just released
https://github.com/os72/protoc-jar/blob/master/RELEASE_NOTES.md

**Comment by MattRMcFarland** [comment]
@os72 @thesamet Thanks for the help and maintaining these great tools!

**Comment by thesamet** [comment]
sbt-protoc 0.99.4 uses protoc-jar 3.2.0.
