### ISSUE TITLE
Intermittent crash with protoc not found

### ISSUE THREAD

**Issue by adampauls** [thesamet/sbt-protoc#179]
Sometimes, our CI system will fail with the exception attached below. It is not reliably reproducible, so I suspect some sort of race condition. The `.exe` suffix worries me a bit since this is not happening on windows, but from poking around that seems to be normal. One possibly relevant bit of information is that we have several sbt projects in this, most of which have the ProtocPlugin disabled. I wonder if the plugin tries to download `protoc` once for each project or something?

We are specifying PB.protocVersion = "3.7.1"

```
2020-09-18T16:20:58.2626976Z [error] java.lang.RuntimeException: error occurred while compiling protobuf files: Cannot run program "/agent/_work/1/s/prediction/target/streams/compile/protocExecutable/_global/streams/sbt-protoc-download/protoc-bf162385553faf7da54f895e42ef0e94a01f02a7.exe": error=2, No such file or directory
2020-09-18T16:20:58.2629635Z [error] 	at sbtprotoc.ProtocPlugin$.executeProtoc(ProtocPlugin.scala:366)
2020-09-18T16:20:58.2630849Z [error] 	at sbtprotoc.ProtocPlugin$.compile(ProtocPlugin.scala:414)
2020-09-18T16:20:58.2631894Z [error] 	at sbtprotoc.ProtocPlugin$.compileProto$1(ProtocPlugin.scala:514)
2020-09-18T16:20:58.2633111Z [error] 	at sbtprotoc.ProtocPlugin$.$anonfun$sourceGeneratorTask$4(ProtocPlugin.scala:524)
2020-09-18T16:20:58.2634687Z [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
2020-09-18T16:20:58.2635797Z [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
2020-09-18T16:20:58.2636902Z [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
2020-09-18T16:20:58.2637731Z [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
2020-09-18T16:20:58.2638515Z [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
2020-09-18T16:20:58.2639209Z [error] 	at sbt.Execute.work(Execute.scala:289)
2020-09-18T16:20:58.2639851Z [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
2020-09-18T16:20:58.2640978Z [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
2020-09-18T16:20:58.2641816Z [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
2020-09-18T16:20:58.2642639Z [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-09-18T16:20:58.2643227Z [error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2020-09-18T16:20:58.2644008Z [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-09-18T16:20:58.2644614Z [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-09-18T16:20:58.2645253Z [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-09-18T16:20:58.2645818Z [error] 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-09-18T16:20:58.2647201Z [error] Caused by: java.io.IOException: Cannot run program "/agent/_work/1/s/prediction/target/streams/compile/protocExecutable/_global/streams/sbt-protoc-download/protoc-bf162385553faf7da54f895e42ef0e94a01f02a7.exe": error=2, No such file or directory
2020-09-18T16:20:58.2648150Z [error] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
2020-09-18T16:20:58.2648729Z [error] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
2020-09-18T16:20:58.2649318Z [error] 	at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:75)
2020-09-18T16:20:58.2649944Z [error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:106)
2020-09-18T16:20:58.2650646Z [error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$anonfun$runBuffered$1(ProcessBuilderImpl.scala:154)
2020-09-18T16:20:58.2651314Z [error] 	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
2020-09-18T16:20:58.2651875Z [error] 	at sbt.internal.util.BufferedLogger.buffer(BufferedLogger.scala:111)
2020-09-18T16:20:58.2652507Z [error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.runBuffered(ProcessBuilderImpl.scala:154)
2020-09-18T16:20:58.2653181Z [error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:120)
2020-09-18T16:20:58.2654111Z [error] 	at sbtprotoc.ProtocPlugin$.$anonfun$protobufConfigSettings$24(ProtocPlugin.scala:293)
2020-09-18T16:20:58.2654799Z [error] 	at sbtprotoc.ProtocPlugin$.$anonfun$protobufConfigSettings$24$adapted(ProtocPlugin.scala:289)
2020-09-18T16:20:58.2655432Z [error] 	at protocbridge.ProtocBridge$.runWithGenerators(ProtocBridge.scala:126)
2020-09-18T16:20:58.2655979Z [error] 	at protocbridge.ProtocBridge$.run(ProtocBridge.scala:81)
2020-09-18T16:20:58.2656524Z [error] 	at sbtprotoc.ProtocPlugin$.executeProtoc(ProtocPlugin.scala:360)
2020-09-18T16:20:58.2657067Z [error] 	at sbtprotoc.ProtocPlugin$.compile(ProtocPlugin.scala:414)
2020-09-18T16:20:58.2657602Z [error] 	at sbtprotoc.ProtocPlugin$.compileProto$1(ProtocPlugin.scala:514)
2020-09-18T16:20:58.2658195Z [error] 	at sbtprotoc.ProtocPlugin$.$anonfun$sourceGeneratorTask$4(ProtocPlugin.scala:524)
2020-09-18T16:20:58.2658778Z [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
2020-09-18T16:20:58.2659339Z [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
2020-09-18T16:20:58.2660064Z [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
2020-09-18T16:20:58.2660569Z [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
2020-09-18T16:20:58.2661116Z [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
2020-09-18T16:20:58.2661682Z [error] 	at sbt.Execute.work(Execute.scala:289)
2020-09-18T16:20:58.2662188Z [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
2020-09-18T16:20:58.2663048Z [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
2020-09-18T16:20:58.2663695Z [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
2020-09-18T16:20:58.2664510Z [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-09-18T16:20:58.2665154Z [error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2020-09-18T16:20:58.2665965Z [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-09-18T16:20:58.2666590Z [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-09-18T16:20:58.2667392Z [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-09-18T16:20:58.2667945Z [error] 	at java.base/java.lang.Thread.run(Thread.java:834)
2020-09-18T16:20:58.2668467Z [error] Caused by: java.io.IOException: error=2, No such file or directory
2020-09-18T16:20:58.2668981Z [error] 	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
2020-09-18T16:20:58.2669479Z [error] 	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:340)
2020-09-18T16:20:58.2670053Z [error] 	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:271)
2020-09-18T16:20:58.2670606Z [error] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
2020-09-18T16:20:58.2671142Z [error] 	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
2020-09-18T16:20:58.2671736Z [error] 	at scala.sys.process.ProcessBuilderImpl$Simple.run(ProcessBuilderImpl.scala:75)
2020-09-18T16:20:58.2672374Z [error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.run(ProcessBuilderImpl.scala:106)
2020-09-18T16:20:58.2673059Z [error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$anonfun$runBuffered$1(ProcessBuilderImpl.scala:154)
2020-09-18T16:20:58.2673729Z [error] 	at scala.runtime.java8.JFunction0$mcI$sp.apply(JFunction0$mcI$sp.java:23)
2020-09-18T16:20:58.2674307Z [error] 	at sbt.internal.util.BufferedLogger.buffer(BufferedLogger.scala:111)
2020-09-18T16:20:58.2674912Z [error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.runBuffered(ProcessBuilderImpl.scala:154)
2020-09-18T16:20:58.2675588Z [error] 	at scala.sys.process.ProcessBuilderImpl$AbstractBuilder.$bang(ProcessBuilderImpl.scala:120)
2020-09-18T16:20:58.2676256Z [error] 	at sbtprotoc.ProtocPlugin$.$anonfun$protobufConfigSettings$24(ProtocPlugin.scala:293)
2020-09-18T16:20:58.2677387Z [error] 	at sbtprotoc.ProtocPlugin$.$anonfun$protobufConfigSettings$24$adapted(ProtocPlugin.scala:289)
2020-09-18T16:20:58.2678110Z [error] 	at protocbridge.ProtocBridge$.runWithGenerators(ProtocBridge.scala:126)
2020-09-18T16:20:58.2678675Z [error] 	at protocbridge.ProtocBridge$.run(ProtocBridge.scala:81)
2020-09-18T16:20:58.2679197Z [error] 	at sbtprotoc.ProtocPlugin$.executeProtoc(ProtocPlugin.scala:360)
2020-09-18T16:20:58.2679738Z [error] 	at sbtprotoc.ProtocPlugin$.compile(ProtocPlugin.scala:414)
2020-09-18T16:20:58.2680258Z [error] 	at sbtprotoc.ProtocPlugin$.compileProto$1(ProtocPlugin.scala:514)
2020-09-18T16:20:58.2680921Z [error] 	at sbtprotoc.ProtocPlugin$.$anonfun$sourceGeneratorTask$4(ProtocPlugin.scala:524)
2020-09-18T16:20:58.2681492Z [error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
2020-09-18T16:20:58.2682045Z [error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
2020-09-18T16:20:58.2682616Z [error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
2020-09-18T16:20:58.2683352Z [error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
2020-09-18T16:20:58.2684010Z [error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
2020-09-18T16:20:58.2684787Z [error] 	at sbt.Execute.work(Execute.scala:289)
2020-09-18T16:20:58.2685901Z [error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
2020-09-18T16:20:58.2686997Z [error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
2020-09-18T16:20:58.2688106Z [error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
2020-09-18T16:20:58.2689035Z [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-09-18T16:20:58.2690028Z [error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
2020-09-18T16:20:58.2690960Z [error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2020-09-18T16:20:58.2691693Z [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2020-09-18T16:20:58.2696334Z [error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2020-09-18T16:20:58.2697663Z [error] 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by thesamet** [comment]
Between 0.99.31 and 1.0.0-RC2 the code that downloads protoc has been completely rewritten. Would be great to focus on the error you are seeing with 1.0.0-RC2. Can you try to create a project that can help reproduce this - even if that project needs to be built multiple times to in order to reproduce the error?

Alternatively, you can try forking sbt-protoc and see if you can add more logging to understand what's going on.

If you also want a quick workaround is to have protoc installed on that CI server and use the PB.protocExecutable in Compile setting to point to it, and circumvent the mechanism that resolves protoc from maven.

**Comment by adampauls** [comment]
The failure occurred both with 0.99.31 and 1.0.0-RC2 and the message posted above is for 1.0.0-RC2. I now believe this has something to do with the way that we are caching the `target` directories in our CI system: we create a tarball of all the `target` directories and unzip them onto a fresh git checkout of the source. 

As a workaround, I have found that running `sbt protobuf:clean` before other commands fixes the issue. Because or the way we are caching, we are always recompiling the protos in any case, so this is not a performance problem for now.

**Comment by thesamet** [comment]
Hi @adampauls  In 1.0.0-RC3 we completely reworked the way protoc is cached and I believe this issue should be resolved. Can you take a look and provide feedback?

**Comment by thesamet** [comment]
@adampauls , does it still happen? Let me know if we can close.

**Comment by thesamet** [comment]
I believe the issue is resolved in the newer RC releases. Closing due to inactivity.

**Comment by wedaly** [comment]
hi @thesamet , I work on the same team as @adampauls .  Just wanted to let you know that we upgraded to the most recent 1.0.0, and it looks like the issue has been resolved on our end!  Thanks for the fix!

**Comment by thesamet** [comment]
Thanks for confirming!
