### ISSUE TITLE
crash on sbt initialization with 1.2.x

### ISSUE THREAD

**Issue by bjaglin** [thesamet/sbt-protoc#182]
```
[error] java.lang.VerifyError: Instruction type does not match stack map
[error] Exception Details:
[error]   Location:
[error]     sbtprotoc/ProtocPlugin$.makeArtifact(Lprotocbridge/Artifact;)Lsbt/librarymanagement/ModuleID; @40: invokevirtual
[error]   Reason:
[error]     Type 'sbt/librarymanagement/Disabled$' (current frame, stack[1]) is not assignable to 'sbt/librarymanagement/CrossVersion' (stack map, stack[1])
[error]   Current Frame:
[error]     bci: @40
[error]     flags: { }
[error]     locals: { 'sbtprotoc/ProtocPlugin$', 'protocbridge/Artifact' }
[error]     stack: { 'sbt/librarymanagement/ModuleID', 'sbt/librarymanagement/Disabled$' }
[error]   Stackmap Frame:
[error]     bci: @40
[error]     flags: { }
[error]     locals: { 'sbtprotoc/ProtocPlugin$', 'protocbridge/Artifact' }
[error]     stack: { 'sbt/librarymanagement/ModuleID', 'sbt/librarymanagement/CrossVersion' }
[error]   Bytecode:
[error]     0000000: b204 722b b604 772b b604 7a2b b604 7db6
[error]     0000010: 0480 2bb6 0483 9900 0cb2 0488 b604 8ca7
[error]     0000020: 0009 b201 2eb6 0490 b604 962b b604 9ab6
[error]     0000030: 049e b0                                
[error]   Stackmap Table:
[error]     same_locals_1_stack_item_frame(@34,Object[#1170])
[error]     full_frame(@40,{Object[#2],Object[#1140]},{Object[#1170],Object[#1184]})
[error] 
[error] 	at java.base/java.lang.Class.forName0(Native Method)
[error] 	at java.base/java.lang.Class.forName(Class.java:398)
[error] 	at sbt.internal.inc.ModuleUtilities$.getObject(ModuleUtilities.scala:20)
[error] 	at sbt.internal.inc.ModuleUtilities$.getCheckedObject(ModuleUtilities.scala:27)
[error] 	at sbt.internal.inc.ModuleUtilities$.$anonfun$getCheckedObjects$1(ModuleUtilities.scala:31)
[error] 	at scala.collection.immutable.Stream.$anonfun$map$1(Stream.scala:414)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1167)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1157)
[error] 	at scala.collection.generic.Growable.loop$1(Growable.scala:53)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:57)
[error] 	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:49)
[error] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:185)
[error] 	at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:43)
[error] 	at scala.collection.TraversableLike.$plus$plus(TraversableLike.scala:146)
[error] 	at scala.collection.TraversableLike.$plus$plus$(TraversableLike.scala:142)
[error] 	at scala.collection.immutable.List.$plus$plus(List.scala:206)
[error] 	at sbt.internal.PluginDiscovery$.discoverAll(PluginDiscovery.scala:56)
[error] 	at sbt.internal.Load$.loadPlugins(Load.scala:1318)
[error] 	at sbt.internal.Load$.loadPluginDefinition(Load.scala:1263)
[error] 	at sbt.internal.Load$.buildPlugins(Load.scala:1242)
[error] 	at sbt.internal.Load$.plugins(Load.scala:1225)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$2(Load.scala:694)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.$anonfun$loadUnit$1(Load.scala:694)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.loadUnit(Load.scala:688)
[error] 	at sbt.internal.Load$.$anonfun$builtinLoader$4(Load.scala:484)
[error] 	at sbt.internal.BuildLoader$.$anonfun$componentLoader$5(BuildLoader.scala:176)
[error] 	at sbt.internal.BuildLoader.apply(BuildLoader.scala:241)
[error] 	at sbt.internal.Load$.loadURI$1(Load.scala:546)
[error] 	at sbt.internal.Load$.loadAll(Load.scala:562)
[error] 	at sbt.internal.Load$.loadURI(Load.scala:492)
[error] 	at sbt.internal.Load$.load(Load.scala:471)
[error] 	at sbt.internal.Load$.$anonfun$apply$1(Load.scala:251)
[error] 	at sbt.internal.Load$.timed(Load.scala:1395)
[error] 	at sbt.internal.Load$.apply(Load.scala:251)
[error] 	at sbt.internal.Load$.defaultLoad(Load.scala:69)
[error] 	at sbt.BuiltinCommands$.liftedTree1$1(Main.scala:829)
[error] 	at sbt.BuiltinCommands$.doLoadProject(Main.scala:829)
[error] 	at sbt.BuiltinCommands$.$anonfun$loadProjectImpl$2(Main.scala:800)
[error] 	at sbt.Command$.$anonfun$applyEffect$4(Command.scala:142)
[error] 	at sbt.Command$.$anonfun$applyEffect$2(Command.scala:137)
[error] 	at sbt.Command$.process(Command.scala:181)
[error] 	at sbt.MainLoop$.processCommand(MainLoop.scala:151)
[error] 	at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:139)
[error] 	at sbt.State$$anon$1.runCmd$1(State.scala:246)
[error] 	at sbt.State$$anon$1.process(State.scala:250)
[error] 	at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:139)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.MainLoop$.next(MainLoop.scala:139)
[error] 	at sbt.MainLoop$.run(MainLoop.scala:132)
[error] 	at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:110)
[error] 	at sbt.io.Using.apply(Using.scala:22)
[error] 	at sbt.MainLoop$.runWithNewLog(MainLoop.scala:104)
[error] 	at sbt.MainLoop$.runAndClearLast(MainLoop.scala:59)
[error] 	at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:44)
[error] 	at sbt.MainLoop$.runLogged(MainLoop.scala:35)
[error] 	at sbt.StandardMain$.runManaged(Main.scala:138)
[error] 	at sbt.xMain.run(Main.scala:89)
[error] 	at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
[error] 	at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
[error] 	at xsbt.boot.Launch$.run(Launch.scala:111)
[error] 	at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
[error] 	at xsbt.boot.Launch$.launch(Launch.scala:119)
[error] 	at xsbt.boot.Launch$.apply(Launch.scala:20)
[error] 	at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error] 	at xsbt.boot.Boot$.main(Boot.scala:18)
[error] 	at xsbt.boot.Boot.main(Boot.scala)
[error] java.lang.VerifyError: Instruction type does not match stack map
[error] Exception Details:
[error]   Location:
[error]     sbtprotoc/ProtocPlugin$.makeArtifact(Lprotocbridge/Artifact;)Lsbt/librarymanagement/ModuleID; @40: invokevirtual
[error]   Reason:
[error]     Type 'sbt/librarymanagement/Disabled$' (current frame, stack[1]) is not assignable to 'sbt/librarymanagement/CrossVersion' (stack map, stack[1])
[error]   Current Frame:
[error]     bci: @40
[error]     flags: { }
[error]     locals: { 'sbtprotoc/ProtocPlugin$', 'protocbridge/Artifact' }
[error]     stack: { 'sbt/librarymanagement/ModuleID', 'sbt/librarymanagement/Disabled$' }
[error]   Stackmap Frame:
[error]     bci: @40
[error]     flags: { }
[error]     locals: { 'sbtprotoc/ProtocPlugin$', 'protocbridge/Artifact' }
[error]     stack: { 'sbt/librarymanagement/ModuleID', 'sbt/librarymanagement/CrossVersion' }
[error]   Bytecode:
[error]     0000000: b204 722b b604 772b b604 7a2b b604 7db6
[error]     0000010: 0480 2bb6 0483 9900 0cb2 0488 b604 8ca7
[error]     0000020: 0009 b201 2eb6 0490 b604 962b b604 9ab6
[error]     0000030: 049e b0                                
[error]   Stackmap Table:
[error]     same_locals_1_stack_item_frame(@34,Object[#1170])
[error]     full_frame(@40,{Object[#2],Object[#1140]},{Object[#1170],Object[#1184]})
```

**Comment by bjaglin** [comment]
Most likely due to https://github.com/sbt/sbt/issues/5049
