### ISSUE TITLE
sbt-protoc 1.0.0 can't download protoc

### ISSUE THREAD

**Issue by sideeffffect** [thesamet/sbt-protoc#212]
After upgrading `sbt-protoc` from `0.99.34` to `1.0.0`, the build of the project fails with the following exception:
```
[error] sbt.librarymanagement.ResolveException: Error downloading com.google.protobuf:protoc:391
[error]   Not found
[error]   not found: /home/runner/.ivy2/localcom.google.protobuf/protoc/391/ivys/ivy.xml
[error]   not found: repo1.maven.org/maven2/com/google/protobuf/protoc/391/protoc-391.pom
[error] 	at lmcoursier.CoursierDependencyResolution.unresolvedWarningOrThrow(CoursierDependencyResolution.scala:258)
[error] 	at lmcoursier.CoursierDependencyResolution.$anonfun$update$38(CoursierDependencyResolution.scala:227)
[error] 	at scala.util.Either$LeftProjection.map(Either.scala:573)
[error] 	at lmcoursier.CoursierDependencyResolution.update(CoursierDependencyResolution.scala:227)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:60)
[error] 	at sbt.librarymanagement.DependencyResolution.retrieve(DependencyResolution.scala:129)
[error] 	at sbt.librarymanagement.DependencyResolution.retrieve(DependencyResolution.scala:103)
[error] 	at sbtprotoc.ProtocPlugin$.$anonfun$protobufGlobalSettings$11(ProtocPlugin.scala:201)
[error] 	at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$1$$anon$2.block(ExecutionContextImpl.scala:75)
[error] 	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3118)
[error] 	at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$1.blockOn(ExecutionContextImpl.scala:87)
[error] 	at scala.concurrent.package$.blocking(package.scala:146)
[error] 	at sbtprotoc.ProtocPlugin$.$anonfun$protobufGlobalSettings$10(ProtocPlugin.scala:202)
```
https://github.com/avast/grpc-json-bridge/runs/1745401943#step:6:35
https://github.com/avast/grpc-json-bridge/pull/185

This URL indeed doesn't exist:
```
repo1.maven.org/maven2/com/google/protobuf/protoc/391/protoc-391.pom
```
This does:
```
repo1.maven.org/maven2/com/google/protobuf/protoc/3.9.1/protoc-3.9.1.pom
```

It seems like an error in `sbt-protoc`

**Comment by thesamet** [comment]
Thanks for reporting this experience while upgrading. I added a migration section to README.md, and the next release would throw a more actionable error message when this is detected. One of the changes in 1.0.0 is that we no longer depend on protoc-jar. One of the breakages it leads to is that concatenated versions number such as `-v391` no longer work, since now sbt-protoc looks for the given version as-is in maven (after stripping `-v`). Please update `PB.protocVersion` in build.sbt to the version number you are expecting (for example, `"3.9.1"`).

**Comment by sideeffffect** [comment]
Thanks :heart: Worked like a charm
