### ISSUE TITLE
sorry we broke CacheImplicits

### ISSUE THREAD

**Issue by eed3si9n** [thesamet/sbt-protoc#32]
I added a new implicit for `OffsetDateTime` in  https://github.com/eed3si9n/sjson-new/issues/76.

This unfortunately will break `ProtocPlugin` when the next RC comes out:

```scala
[error] java.lang.AbstractMethodError: Method sbtprotoc/ProtocPlugin$.sjsonnew$CalendarFormats$_setter_$offsetDateTimeStringIso_$eq(Lsjsonnew/IsoString;)V is abstract
[error] 	at sbtprotoc.ProtocPlugin$.sjsonnew$CalendarFormats$_setter_$offsetDateTimeStringIso_$eq(ProtocPlugin.scala)
[error] 	at sjsonnew.CalendarFormats.$init$(CalendarFormats.scala:34)
[error] 	at sbtprotoc.ProtocPlugin$.<init>(ProtocPlugin.scala:11)
[error] 	at sbtprotoc.ProtocPlugin$.<clinit>(ProtocPlugin.scala)
```

**Comment by xuwei-k** [comment]
fixed in https://github.com/thesamet/sbt-protoc/pull/33
